# Blog settings
title: Frontboard
tagline: blog o front-endzie
author: Kacper Stawiński
email: kontakt@frontboard.pl
description: >-
  Blog o front-endzie: poradniki, nowości i inspiracje dotyczące programowania.
  Głównie JavaScript, Vue.js, HTML i CSS i coś o dobrych praktykach programisty.
baseurl: ""
url: "https://frontboard.pl"
github_username:  frontboard
facebook_username: frontboardpl
twitter_username: frontboardpl
instagram_username: frontboard_pl
lang: pl
google_analytics: G-SPHS5KD25L

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
permalink: /:title
include: ['_pages']
kramdown:
  syntax_highlighter_opts:
    disable: true

# Pagination settings
paginate: 9
paginate_path: /strona-:num
seo_paginator_message: "Strona %<current>s | "

# Disqus comments
disqus:
  shortname: jsw60dni

# Categories
categories_names:
  'javascript': 'JavaScript'
  'vue': 'Vue.js'
  'inne': 'Po godzinach'
  'html': 'HTML'
  'css': 'CSS'
