# Blog settings
title: Frontboard
author: Kacper Stawiński
email: kontakt@frontboard.pl
description: >-
  Notatki front-end developera. Mini-blog, który służy zbieraniu
  interesujących i przede wszystkim przydatnych w pracy programisty treści.
baseurl: ""
url: "https://frontboard.pl"
github_username:  kstawinski
lang: pl

# Build settings
theme: minima
plugins:
  - jekyll-feed
permalink: /:title
