# Blog settings
title: Frontboard
author: Kacper Stawiński
email: kontakt@frontboard.pl
description: >-
  Notatki front-end developera. Mini-blog, który służy zbieraniu
  interesujących i przede wszystkim przydatnych w pracy programisty treści.
baseurl: ""
url: "https://frontboard.pl"
github_username:  frontboard
facebook_username: frontboardpl
lang: pl
google_analytics: G-SPHS5KD25L

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
permalink: /:title
include: ['_pages']

# Pagination settings
paginate: 5
paginate_path: /strona-:num
seo_paginator_message: "Strona %<current>s | "

# Disqus comments
disqus:
  shortname: jsw60dni